server:
  port: 9000
spring:
  application:
    name: client-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://registiration-server:8761/eureka
  instance:
    prefer-ip-address: true